[workspace]
resolver = "3"
members = ["client", "server", "utils"]

[workspace.dependencies]
aes-gcm-siv = "0.11.1"
p256 = {version = "0.13.2", features = ["ecdh"]}
rsa = "0.9.8"
sha3 = "0.10.8"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

