[package]
name = "server"
version = "0.1.0"
edition = "2024"
default-run = "server"

[dependencies]
#rocksdb = "0.23.0"
p256.workspace = true
rsa.workspace = true
rand.workspace = true
rand_new.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
utils = {path = "../utils"}