[package]
name = "server"
version = "0.1.0"
edition = "2024"
default-run = "server"

[dependencies]
aes-gcm-siv.workspace = true
p256.workspace = true
rsa.workspace = true
sha3.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
utils = {path = "../utils"}