[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
chacha20poly1305.workspace = true
rsa.workspace = true
sha3.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true